services:
  api:
    image: ghcr.io/web3kt/api-explorer:latest
    container_name: api
    environment:
      MYSQL_URL: mysql:3306
      MYSQL_DATABASE: explorer
      MYSQL_USER: explorer
      MYSQL_PASSWORD: password
      BESU_RPC_URL: ${RPC_ENDPOINT}
    depends_on:
      mysql:
        condition: service_healthy
  web:
    image: ghcr.io/web3kt/web-explorer:latest
    container_name: web
    environment:
      PUBLIC_SYMBOL: ETH
      PUBLIC_API_ENDPOINT: http://api:8080
    ports:
      - 3000:3000
    depends_on:
      - api
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: explorer
      MYSQL_USER: explorer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
