services:
  api:
    image: ghcr.io/web3kt/api-explorer:latest
    container_name: api
    environment:
      MYSQL_URL: mysql:3306
      MYSQL_DATABASE: explorer
      MYSQL_USER: explorer
      MYSQL_PASSWORD: password
      RPC_ENDPOINT: http://besu:8545
    depends_on:
      mysql:
        condition: service_healthy
  web:
    image: ghcr.io/web3kt/web-explorer:latest
    container_name: web
    environment:
      PUBLIC_SYMBOL: ETH
      PUBLIC_API_ENDPOINT: http://api:8080
    ports:
      - 3000:3000
    depends_on:
      - api
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ${DATAPATH:-./data}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: explorer
      MYSQL_USER: explorer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
  besu:
    image: hyperledger/besu:latest
    restart: always
    container_name: besu
    environment:
      BESU_DATA_PATH: /var/lib/besu
      BESU_DATA_STORAGE_FORMAT: FOREST
      BESU_ENGINE_HOST_ALLOWLIST: "*"
      BESU_ENGINE_JWT_SECRET: /var/lib/besu/jwtsecret.hex
      BESU_ENGINE_RPC_ENABLED: true
      BESU_HOST_ALLOWLIST: "*"
      BESU_RPC_HTTP_CORS_ORIGINS: all
      BESU_RPC_HTTP_ENABLED: true
      BESU_RPC_HTTP_HOST: 0.0.0.0
      BESU_RPC_HTTP_MAX_ACTIVE_CONNECTIONS: 4096
      BESU_RPC_HTTP_API: ETH,NET,WEB3,TXPOOL,TRACE
      BESU_SYNC_MODE: X_SNAP
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - ${DATAPATH:-./data}/besu:/var/lib/besu
  teku:
    image: consensys/teku:latest
    restart: always
    container_name: teku
    environment:
      TEKU_DATA_BASE_PATH: /var/lib/teku
      TEKU_EE_ENDPOINT: http://besu:8551
      TEKU_EE_JWT_SECRET_FILE: /var/lib/teku/jwtsecret.hex
      TEKU_INITIAL_STATE: https://beaconstate-mainnet.chainsafe.io/eth/v2/debug/beacon/states/finalized
      TEKU_LOG_DESTINATION: CONSOLE
    depends_on:
      - besu
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
    volumes:
      - ${DATAPATH:-./data}:/var/lib/teku
